// Seed data for testing launch verification

export const seedLinks = [
  // Active links
  {
    id: '1',
    slug: 'tickets',
    destination_url: 'https://shamrockrovers.ie/tickets',
    title: 'Match Tickets',
    campaign: 'tickets',
    channel: 'Tickets',
    owner: 'bill',
    status: 'active',
    redirect_code: 301,
    created_by: 'bill',
    created_at: new Date().toISOString(),
    updated_by: 'bill',
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'shop',
    destination_url: 'https://shop.shamrockrovers.ie',
    title: 'Club Shop',
    campaign: 'shop',
    channel: 'Other',
    owner: 'bill',
    status: 'active',
    redirect_code: 301,
    created_by: 'bill',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_by: 'bill',
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'bohs',
    destination_url: 'https://shamrockrovers.ie/tickets?utm_source=rovrs&utm_medium=social&utm_campaign=bohs',
    title: 'Bohs Match',
    campaign: 'bohs',
    channel: 'Matchday',
    owner: 'marketing',
    status: 'active',
    redirect_code: 302,
    opponent: 'Bohemians',
    competition: 'League of Ireland',
    match_date: '2024-05-10',
    home_away: 'home',
    created_by: 'marketing',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_by: 'marketing',
    updated_at: new Date().toISOString(),
  },

  // Social variants
  {
    id: '4',
    slug: 'bohs-ig',
    destination_url: 'https://shamrockrovers.ie/tickets?utm_source=instagram&utm_medium=social&utm_campaign=bohs',
    title: 'Bohs Match - Instagram',
    campaign: 'bohs',
    channel: 'Instagram',
    owner: 'social',
    status: 'active',
    redirect_code: 302,
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'bohs',
    created_by: 'social',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    slug: 'bohs-fb',
    destination_url: 'https://shamrockrovers.ie/tickets?utm_source=facebook&utm_medium=social&utm_campaign=bohs',
    title: 'Bohs Match - Facebook',
    campaign: 'bohs',
    channel: 'Facebook',
    owner: 'social',
    status: 'active',
    redirect_code: 302,
    utm_source: 'facebook',
    utm_medium: 'social',
    utm_campaign: 'bohs',
    created_by: 'social',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // QR code links
  {
    id: '6',
    slug: 'bohs-qr',
    destination_url: 'https://shamrockrovers.ie/tickets?utm_source=qr&utm_medium=offline&utm_campaign=bohs',
    title: 'Bohs Match - QR',
    campaign: 'bohs',
    channel: 'QR code',
    owner: 'marketing',
    status: 'active',
    redirect_code: 302,
    is_qr: true,
    utm_source: 'qr',
    utm_medium: 'offline',
    utm_campaign: 'bohs',
    expires_at: new Date(Date.now() + 604800000).toISOString(), // Expires in 7 days
    created_by: 'marketing',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Offsite ticket link
  {
    id: '7',
    slug: 'dundalk-tickets',
    destination_url: 'https://dundalkfc.ie/tickets',
    title: 'Dundalk Match Tickets',
    campaign: 'dundalk',
    channel: 'Tickets',
    owner: 'bill',
    status: 'active',
    redirect_code: 302,
    is_offsite_ticket: true,
    show_offsite_preview: true,
    created_by: 'bill',
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Expired link
  {
    id: '8',
    slug: 'expired-game',
    destination_url: 'https://shamrockrovers.ie/tickets',
    title: 'Expired Match',
    campaign: 'expired',
    channel: 'Matchday',
    owner: 'marketing',
    status: 'expired',
    redirect_code: 302,
    expires_at: new Date(Date.now() - 86400000).toISOString(), // Yesterday
    created_by: 'marketing',
    created_at: new Date(Date.now() - 604800000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Paused link
  {
    id: '9',
    slug: 'paused-campaign',
    destination_url: 'https://shamrockrovers.ie/tickets',
    title: 'Paused Campaign',
    campaign: 'paused',
    channel: 'Other',
    owner: 'bill',
    status: 'paused',
    redirect_code: 302,
    created_by: 'bill',
    created_at: new Date(Date.now() - 345600000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Deleted link (slug can be reused)
  {
    id: '10',
    slug: 'deleted-link',
    destination_url: 'https://shamrockrovers.ie/tickets',
    title: 'Deleted Link',
    campaign: 'test',
    channel: 'Other',
    owner: 'bill',
    status: 'deleted',
    redirect_code: 302,
    created_by: 'bill',
    created_at: new Date(Date.now() - 518400000).toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString(),
  },

  // Auto-generated random slug
  {
    id: '11',
    slug: 'x7k2a',
    destination_url: 'https://shamrockrovers.ie/tickets?utm_source=social&utm_medium=quick&utm_campaign=general',
    title: 'Quick Link',
    campaign: 'general',
    channel: 'Social',
    owner: 'social',
    status: 'active',
    redirect_code: 302,
    created_by: 'auto',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const seedUsers = [
  // Admin users
  {
    id: '1',
    email: 'bill@shamrockrovers.ie',
    name: 'Bill',
    role: 'admin',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    email: 'marketing@shamrockrovers.ie',
    name: 'Marketing Team',
    role: 'editor',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    email: 'social@shamrockrovers.ie',
    name: 'Social Media',
    role: 'editor',
    created_at: new Date().toISOString(),
  },

  // Auto-created users
  {
    id: '4',
    email: 'user@example.com',
    name: 'Test User',
    role: 'editor',
    created_at: new Date().toISOString(),
  },
];

export const seedClickEvents = [
  // Clicks for active tickets link
  {
    id: '1',
    link_id: '1',
    slug: 'tickets',
    clicked_at: new Date().toISOString(),
    country: 'IE',
    referrer: 'https://shamrockrovers.ie',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    device_type: 'desktop',
    utm_source: 'direct',
    utm_medium: 'direct',
    utm_campaign: 'tickets',
  },
  {
    id: '2',
    link_id: '1',
    slug: 'tickets',
    clicked_at: new Date(Date.now() - 3600000).toISOString(),
    country: 'IE',
    referrer: 'https://google.ie',
    user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X)',
    device_type: 'mobile',
    utm_source: 'organic',
    utm_medium: 'search',
    utm_campaign: 'tickets',
  },

  // Clicks for Bohs match
  {
    id: '3',
    link_id: '3',
    slug: 'bohs',
    clicked_at: new Date(Date.now() - 7200000).toISOString(),
    country: 'IE',
    referrer: 'https://instagram.com',
    user_agent: 'Mozilla/5.0 (Linux; Android 11; SM-G991B) AppleWebKit/537.36',
    device_type: 'mobile',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'bohs',
  },

  // QR scan
  {
    id: '4',
    link_id: '6',
    slug: 'bohs-qr',
    clicked_at: new Date(Date.now() - 10800000).toISOString(),
    country: 'IE',
    referrer: '',
    user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X)',
    device_type: 'mobile',
    utm_source: 'qr',
    utm_medium: 'offline',
    utm_campaign: 'bohs',
  },
];