name = "rovrs"
main = "packages/redirect-worker/src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

[env.development]
vars = { ENVIRONMENT = "development" }

[[d1_databases]]
binding = "DB"
database_name = "rovrs"
database_id = "your-database-id"