name = "rovrs-archival"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[triggers]
crons = ["0 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "rovrs-db"
database_id = "7c172f99-9550-4aa7-a33f-165fc340a051"

[[r2_buckets]]
binding = "ARCHIVE"
bucket_name = "rovrs-click-archive"

[vars]
RETENTION_DAYS = "180"
