name = "rovrs-queue-consumer"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
[queues.producer]
queue = "click-events"
binding = "CLICK_EVENTS_QUEUE"

[env.staging]
[queues.producer]
queue = "click-events-staging"
binding = "CLICK_EVENTS_QUEUE"

[env.development]
[queues.producer]
queue = "click-events-dev"
binding = "CLICK_EVENTS_QUEUE"